---
- hosts: localhost
  connection: local
  vars:
    #account_file: '/home/dataylor/Downloads/redhat-lab-311219-18edacc3b415.json'
    gcp_image_name: rhel7.9_golden_image
    selected_os: rhel79
    disk_to_upload: "/tmp/{{ images[selected_os].output }}.tmp.vmdk"
    gcp_storage_bucket: dataylor-bucket2
    #gcp_project: redhat-lab-311219
    gcp_auth_kind: serviceaccount
  tasks:
  - name: create a bucket
    google.cloud.gcp_storage_bucket:
      name: "{{ gcp_storage_bucket }}"
      auth_kind: "{{ gcp_auth_kind }}"
      #project: "{{ gcp_project }}"
      #service_account_file: "{{ account_file }}"
      state: present
    ignore_errors: yes

  - name: create a object
    google.cloud.gcp_storage_object:
      action: upload
      bucket: "{{ gcp_storage_bucket }}"
      src: "{{ disk_to_upload }}"
      dest: "{{ gcp_image_name }}"
      auth_kind: "{{ gcp_auth_kind }}"
      #project: redhat-lab-311219
      #service_account_file: "{{ account_file }}"

