---
- hosts: all
  vars:
    # lookup file or paste the pub key here
    public_key: lookup('file', '/home/dataylor/ansiblesvc.pub')
    #public_key: "ssh-rsa AAAAB3Nz ...blah... 03Ug30uAv8= you@there.com"
  tasks:
  - name: "logging in as root"
    shell: "echo hi"

  - name: Add the user 'ansiblesvc'
    user:
      name: ansiblesvc
      comment: "Build for Automation"
      group: wheel

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: ansiblesvc
      state: present
      key: "{{ public_key }}"

