---
- hosts: all
  vars:
    username: ansiblesvc
    groups: "wheel,{{ username }}"
    # provide path to a public keyfile or paste in the pub key
    public_key: lookup('file', '/home/dataylor/ansiblesvc.pub')
    #public_key: "ssh-rsa AAAAB3Nz ...blah... 03Ug30uAv8= you@there.com"
  tasks:
  - name: "Add the automation user '{{ username }}'"
    user:
      name: "{{ username }}"
      comment: "Built By Ansible Automation"
      group: "{{ groups }}"

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ public_key }}"

  - name:
    template:
      src: "{{ username }}.j2"
      dest: "/etc/sudoers.d/{{ username }}"
      owner: root
      group: root
      mode: '0440'

