# play 1
- name: "Customize qcow2 image, convert to vmdk and copy to esxi datastore"
  hosts: builders
  tags: image
  vars:
    ESXIHOSTS:
      - 10.55.102.158
      - 10.55.102.159
    REQUIREDRPMS: "jq open-vm-tools"
    COPYIN:
      - download.sh
      - firstboot.sh
    OFFLINE_TOKEN: "{{ rhsm_token }}"
    SUBUSER: "{{ rhsm_username }}"
    SUBPASS: "{{ rhsm_password }}"
  environment:
    LIBGUESTFS_BACKEND: direct
  tasks:
  - name: Customize the image
    ansible.builtin.include_tasks: esxi-customize-image.yml

# play 2
- name: "Run vmfstools on new vmdk and make golden image"
  hosts: esxi-hosts
  tags: esxi
  tasks:
  - name: Prep the vmdk
    ansible.builtin.include_tasks: esxi-vmdk-convert.yml

