# play 1
- name: "Prep the esxi pub key for builder"
  hosts: esxi-hosts
  tags: esxi
  tasks:
  - name: ssh keys
    block:
    - name: "esxi_host: Ensure builder ssh key is set"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/{{ SSHPUBKEY }}.j2"
        dest: "/etc/ssh/keys-root/authorized_keys"
        backup: yes
        remote_src: no

# play 2
- name: "Customize qcow2 image, convert to vmdk and copy to esxi datastore"
  hosts: builders
  tags: image
  vars:
    ESXIHOSTS:
      - 10.55.102.160
      - 10.55.102.161
    REQUIREDRPMS: "jq open-vm-tools python3"
    COPYIN:
      - download.sh
      - firstboot.sh
    OFFLINE_TOKEN: "{{ rhsm_token }}"
    SUBUSER: "{{ rhsm_username }}"
    SUBPASS: "{{ rhsm_password }}"
    mount_path: /mnt/vmdks
    nfs_target: 10.55.102.34:/mnt/mycloud1/vmdks
  environment:
    LIBGUESTFS_BACKEND: direct
  tasks:
  - name: Customize the image
    ansible.builtin.include_tasks: "esxi-customize-{{ osflavor }}-image.yml"

# play 3
- name: "Run vmfstools on new vmdk and make golden image"
  hosts: esxi-hosts
  tags: esxi
  tasks:
  - name: Prep the vmdk
    ansible.builtin.include_tasks: esxi-vmdk-convert.yml

