  - name: "grab access token from redhat cdn"
    ansible.builtin.uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: refresh_token
        client_id: rhsm-api
        refresh_token: "{{ rhsm_token }}"
      status_code: [304,200]
      return_content: yes
    register: access_token

  - name: "grab filename from redhat cdn"
    ansible.builtin.uri:
      url: "https://api.access.redhat.com/management/v1/images/{{ images[selected_os].chksum }}/download"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token.json.access_token }}"
      status_code: [304,200]
    register: imageraw

  - name: "Check if image file exists in playbook dir"
    stat:
      path: "{{ playbook_dir }}/{{ images[selected_os].input }}"
    register: playimage

  - name: "Check if image file exists at target now"
    stat:
      path: "/tmp/{{ images[selected_os].input }}"
    register: diskimage

  - name: "save {{ images[selected_os].input }} to environment"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/{{ images[selected_os].input }}"
      dest: "/tmp/{{ images[selected_os].input }}"
      owner: root
      group: root
      mode: '0644'
    when:
      - ( ( playimage.stat.exists == true ) and ( diskimage.stat.exists == false ) and ( playimage.stat.checksum == images[selected_os].chksum ) ) or ( ( playimage.stat.exists == true ) and ( diskimage.stat.exists == true ) and ( diskimage.stat.checksum != images[selected_os].chksum ) and ( playimage.stat.checksum == images[selected_os].chksum ) )

  - name: wrapper for download
    block:
    - name: "save correct {{ images[selected_os].input }} to disk"
      uri:
        url: "{{ imageraw.url }}"
        method: GET
        dest: "/tmp/{{ images[selected_os].input }}"
        status_code: [304,200]
        headers:
          Authorization: "Bearer {{ access_token.json.access_token }}"
    when: 
      - ( diskimage.stat.exists == false ) or ( diskimage.stat.checksum != images[selected_os].chksum )

    rescue:
    - name: "Download Block Wrapper completed"
      debug: msg="Well that didn't work"

  - name: "preflight checks"
    block:
    - name: "[preflight] check if libguestfs-tools is installed"
      shell: rpm -qa | grep libguestfs-tools

    rescue:
      - name: "You need to install thelibguestfs-tools rpm. Ctrl-C to stop, or wait to continue"
        debug:
          msg: "Run 'sudo dnf -y install libguestfs-tools' to install the needed tools"
      - name: "Please wait 10 secs"
        pause:
          seconds: 10
      - name: "installing libguestfs-tools"
        yum:
          name: libguestfs-tools
          state: present
        become: yes

  - name: "Delete custom working custom image"
    file:
      path: "/tmp/{{ images[selected_os].input }}.custom"
      state: absent

  - name: "builder: working from backup of image {{ images[selected_os].input }}"
    ansible.builtin.copy:
      src: "/tmp/{{ images[selected_os].input }}"
      dest: "/tmp/{{ images[selected_os].input }}.custom"
      backup: no
      remote_src: yes

  - name: "builder: Copy in the scripts"
    ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/tmp/{{ item }}"
      owner: root
      group: root
      mode: '0744'
    become: yes
    loop:
      - download.sh
      - firstboot.sh
      - "{{ SSHPUBKEY }}"

  - name: "builder: remove old vmdk if it exists"
    file:
      path: "/tmp/{{ images[selected_os].output }}.tmp.vmdk"
      state: absent

  - name: "builder: setting the root password"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --root-password password:{{ supersecretpassword }}

  - name: "builder: customizing hostname"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --hostname {{ images[selected_os].output }}

  - name: "builder: injecting ssh key"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --ssh-inject root:file:/tmp/{{ SSHPUBKEY }}

  - name: "builder: registering and subscribing, change to use satellite here"
    shell: |
      virt-customize -v -x -a /tmp/{{ images[selected_os].input }}.custom --run-command "subscription-manager register \
        --username={{ rhsm_username }} \
        --password='{{ rhsm_password }}' \
        --auto-attach \
        --force"

  - name: "builder: customizing add base"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --run-command "yum -y install {{ REQUIREDRPMS }}"
    ignore_errors: yes

  - name: "builder: adding scripts to /root"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --copy-in /tmp/{{ item }}:/root
    loop: "{{ COPYIN }}"

  - name: "builder: adding growdisk script to firstboot"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --firstboot /tmp/firstboot.sh

  - name: "builder: tell selinux to relabel next boot"
    shell: |
      virt-customize -a /tmp/{{ images[selected_os].input }}.custom --run-command "touch /.autorelabel"

  - name: "builder: running qemu-convert to vmdk"
    shell: |
      qemu-img convert /tmp/{{ images[selected_os].input }}.custom -O vmdk -o adapter_type=lsilogic,subformat=streamOptimized,compat6 /tmp/{{ images[selected_os].output }}.tmp.vmdk -p
    become: yes

  - name: "builder: copy to esxi hosts"
    shell: |
      scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/builder /tmp/{{ images[selected_os].output }}.tmp.vmdk root@{{ item }}:{{ VMWROOT }}/
    loop: "{{ ESXIHOSTS }}"

  - name: "Ensure storage mount point exists"
    file:
      path: "{{ mount_path }}"
      state: directory
    become: yes

  - name: "Mount nfs share to upload images"
    ansible.posix.mount:
      path: "{{ mount_path }}"
      src: "{{ nfs_target }}"
      boot: no
      fstype: nfs
      opts: noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=1min
      state: present
    become: yes
    ignore_errors: yes

  - name: "Save vmdk to cloud storage"
    copy:
      src: "/tmp/{{ images[selected_os].output }}.tmp.vmdk"
      dest: "{{ mount_path}}/{{ images[selected_os].output }}.tmp.vmdk"
      remote_src: yes
    become: yes
    ignore_errors: yes

  - name: "Unmount nfs share"
    ansible.posix.mount:
      path: "{{ mount_path }}"
      state: unmounted
    become: yes
    ignore_errors: yes

#  - name: "builder: remove tmp vmdk"
#    file:
#      path: "/tmp/{{ images[selected_os].output }}.tmp.vmdk"
#      state: absent

