- name: "Delete a vm in vmware by name"
  hosts: compute4
  vars:
    ESXIHOST: compute4.tfound.org
  tasks:
  - name: "Delete a virtual machine"
    community.vmware.vmware_guest:
      hostname: "{{ ESXIHOST }}"
      username: "{{ VCENTER_USER }}"
      password: "{{ ROOTPASS }}"
      validate_certs: no
      name: "{{ NEWVM }}"
      delete_from_inventory: True
      state: absent
      force: yes
    delegate_to: localhost
    register: deploy

  - name: "what that mouth do?"
    debug: var=deploy

