- name: "Launch a vm in vmware from a golden image and callback to aap for provisioning"
  hosts: "{{ ESXIHOST | default('compute4.tfound.org',True) }}"
  vars:
    ESXIHOSTS: 
      - compute4.tfound.org
      - compute5.tfound.org
  tasks:
  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ item }}'
      username: "{{ VCENTER_USER }}"
      password: "{{ supersecretpassword }}"
      validate_certs: no
    delegate_to: localhost
    register: vminfo
    loop:
    - compute4.tfound.org
    - compute5.tfound.org

  - debug:
      var: item.virtual_machines
    loop: "{{ vminfo.results }}"

