---
- hosts: localhost
  connection: local
  tasks:
  - name: "grab access token from redhat cdn"
    ansible.builtin.uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: refresh_token
        client_id: rhsm-api
        refresh_token: "{{ rhsm_token }}"
      status_code: [304,200]
      return_content: yes
    register: access_token

