---
# check out the directory execution-environments/ to build custom EE
# to install, run ./setup.sh
# or ansible-galaxy install -r requirements.yml
collections:
  - name: community.aws
    version: 1.5.0
  - name: amazon.aws
    version: 1.5.0
  - name: performancecopilot.metrics
    version: 2.2.4
  - name: community.general
  - name: redhat.satellite
