---
# check out the directory execution-environments/ to build custom EE
# to install, run ./setup.sh
# or ansible-galaxy install -r requirements.yml
collections:
  - name: community.aws
    #version: 1.5.0
    source: https://galaxy.ansible.com
  - name: amazon.aws
    #version: 1.5.0
    source: https://galaxy.ansible.com
  - name: performancecopilot.metrics
    version: 2.2.4
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
#  - name: redhat.satellite
