---
# see README.txt
version: 1
ansible_config: ansible.cfg
build_arg_defaults:
  # default as of 11/14/2022
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
    RUN /usr/bin/rpm -ivh https://download.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    RUN /usr/bin/rpm -ivh https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm
    RUN /usr/bin/rpm -ivh  https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
    RUN /usr/bin/microdnf upgrade
    RUN /usr/bin/microdnf --enablerepo codeready-builder-for-rhel-8-x86_64-rpms -y install ffmpeg
  append:
    - RUN ls -alhtr 
