---
# see README.txt
version: 1
ansible_config: ansible.cfg
build_arg_defaults:
  # default as of 11/14/2022
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend: |
    ENV PIPENV_INSTALL_TIMEOUT=9999
    ENV PIPENV_TIMEOUT=999
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN ls -alhtr 
